spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/webdb
    username: webuser
    password: webuser

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  thymeleaf:
    cache: false
